=== sillsdev/machine/src/SIL.Machine.Morphology.HermitCrab/HermitCrabInput.dtd
<!-- Hermit Crab input file DTD
       Based on Maxwell, Mike.  1999.  "Hermit Crab Parsing Engine Specification."  SIL ms. 
-->
<!ELEMENT HermitCrabInput (Language+) >
<!ELEMENT Language (Name, PartsOfSpeech, PhonologicalFeatureSystem*, HeadFeatures?, FootFeatures?, MorphologicalPhonologicalRuleFeatures?, StemNames?, 
                    CharacterDefinitionTable+, NaturalClasses?, Families?, PhonologicalRuleDefinitions?, Strata, MorphemeCoOccurrenceRules?, AllomorphCoOccurrenceRules?, SyntacticRules?) >
<!--
  Note: at most one should be active at a time
  -->
<!ATTLIST Language
  isActive (yes | no) "yes"
>

<!--
   =====================
   PartsOfSpeech
   =====================
-->
<!ELEMENT PartsOfSpeech (PartOfSpeech+) >
<!ELEMENT PartOfSpeech (Name) >
<!ATTLIST PartOfSpeech
  id ID #REQUIRED
>

<!--
   =====================
   FeatureSystems
   =====================
-->
<!ELEMENT PhonologicalFeatureSystem (SymbolicFeature*) >
<!--
  Note: at most one should be active at a time
  -->
<!ATTLIST PhonologicalFeatureSystem
  isActive (yes | no) "yes"
>
<!ELEMENT HeadFeatures ((SymbolicFeature | ComplexFeature)*) >
<!ELEMENT FootFeatures ((SymbolicFeature | ComplexFeature)*) >

<!ELEMENT SymbolicFeature (Name, Symbols) >
<!ATTLIST SymbolicFeature
  id ID #REQUIRED
  isActive (yes | no) "yes"
  defaultSymbol IDREF #IMPLIED
>
<!-- Note: for phonlogical features like [son:+] and [nas:+], we create separate values for "+"; potentially we could reuse them -->
<!ELEMENT Symbols (Symbol+) >
<!ELEMENT Symbol (#PCDATA) >
<!ATTLIST Symbol
  id ID #REQUIRED
>

<!ELEMENT ComplexFeature (Name) >
<!ATTLIST ComplexFeature
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!ELEMENT FeatureValue (FeatureValue*)>
<!--
  feature refers to a SymbolicFeature or ComplexFeature ID
  symbolValues refers to one or more Symbol IDs
  -->
<!ATTLIST FeatureValue
  isActive (yes | no) "yes"
  feature IDREF #REQUIRED
  symbolValues IDREFS #IMPLIED
>

<!--
   =====================
   MorphologicalPhonologicalRuleFeatures
   =====================
-->
<!ELEMENT MorphologicalPhonologicalRuleFeatures (MorphologicalPhonologicalRuleFeature+, MorphologicalPhonologicalRuleFeatureGroup*) >
<!ELEMENT MorphologicalPhonologicalRuleFeature (#PCDATA) >
<!ATTLIST MorphologicalPhonologicalRuleFeature
  id ID #REQUIRED
  isActive (yes | no) "yes"
>
<!ELEMENT MorphologicalPhonologicalRuleFeatureGroup (Name)>
<!ATTLIST MorphologicalPhonologicalRuleFeatureGroup
  isActive (yes | no) "yes"
  matchType (any | all) "any"
  outputType (overwrite | append) "overwrite"
  features IDREFS #REQUIRED
>

<!--
   =====================
   StemNames
   =====================
-->
<!ELEMENT StemNames (StemName+) >
<!ELEMENT StemName (Name, Regions) >
<!ATTLIST StemName
  id ID #REQUIRED
  partsOfSpeech IDREFS #REQUIRED
>
<!ELEMENT Regions (Region+) >
<!ELEMENT Region (AssignedHeadFeatures?, AssignedFootFeatures?) >

<!--
   =====================
   CharacterDefinitionTable
   =====================
-->
<!ELEMENT CharacterDefinitionTable (Name, SegmentDefinitions, BoundaryDefinitions? ) >
<!ATTLIST CharacterDefinitionTable
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!ELEMENT Name (#PCDATA) >

<!ELEMENT SegmentDefinitions (SegmentDefinition+) >

<!ELEMENT SegmentDefinition (Representations, FeatureValue*) >
<!ATTLIST SegmentDefinition
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!ELEMENT Representations (Representation+) >

<!ELEMENT Representation (#PCDATA) >

<!ELEMENT BoundaryDefinitions (BoundaryDefinition+) >

<!ELEMENT BoundaryDefinition (Representations) >
<!ATTLIST BoundaryDefinition
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!--
   =====================
   NaturalClasses
   =====================
-->
<!ELEMENT NaturalClasses (FeatureNaturalClass | SegmentNaturalClass)+ >

<!ELEMENT FeatureNaturalClass (Name, FeatureValue*) >
<!ATTLIST FeatureNaturalClass 
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!ELEMENT SegmentNaturalClass (Name, Segment*) >
<!ATTLIST SegmentNaturalClass 
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!--
   =====================
   Families
   =====================
-->
<!-- Families are used to block analyses for irregular forms (e.g. preventing the regular form from also analyzing) -->
<!ELEMENT Families (Family*) >
<!ELEMENT Family (#PCDATA) >
<!ATTLIST Family
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!--
   =====================
   PhonologicalRuleDefinitions
   =====================
-->
<!ELEMENT PhonologicalRuleDefinitions (PhonologicalRule | MetathesisRule)*>

<!ELEMENT PhonologicalRule (Name, VariableFeatures?, PhoneticInput, PhonologicalSubrules)>
<!ATTLIST PhonologicalRule
  id ID #REQUIRED
  isActive (yes | no) "yes"
  multipleApplicationOrder (leftToRightIterative | rightToLeftIterative | simultaneous) "leftToRightIterative"
>

<!ELEMENT PhoneticInput (PhoneticSequence?) >

<!ELEMENT PhonologicalSubrules (PhonologicalSubrule+) >
<!ELEMENT PhonologicalSubrule (PhoneticOutput, Environment?, PreviousWord?, NextWord?) >
<!--
  requiredPartsOfSpeech refers to one or more PartOfSpeech IDs
  requiredMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
  excludedMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
-->  
<!ATTLIST PhonologicalSubrule
  isActive (yes | no) "yes"
  requiredPartsOfSpeech IDREFS #IMPLIED
  requiredMPRFeatures IDREFS #IMPLIED
  excludedMPRFeatures IDREFS #IMPLIED
>

<!ELEMENT PhoneticOutput (PhoneticSequence?) >
  
<!ELEMENT LeftEnvironment (PhoneticTemplate) >
<!ELEMENT RightEnvironment (PhoneticTemplate) >

<!ELEMENT PreviousWord (PhoneticTemplate | Null) >
<!ATTLIST PreviousWord
  id ID #REQUIRED
  >
<!ELEMENT NextWord (PhoneticTemplate | Null) >
<!ATTLIST NextWord
  id ID #REQUIRED
  >

<!ELEMENT Null EMPTY >
<!ATTLIST Null
  id ID #REQUIRED
>

<!ELEMENT MetathesisRule (Name, StructuralDescription) >
<!ATTLIST MetathesisRule
  isActive (yes | no) "yes"
  id ID #REQUIRED
  leftSwitch IDREF #REQUIRED
  rightSwitch IDREF #REQUIRED
  multipleApplicationOrder (leftToRightIterative | rightToLeftIterative) "leftToRightIterative"
>

<!ELEMENT StructuralDescription (PhoneticTemplate) >

<!--
   =====================
   Strata
   =====================
-->
<!ELEMENT Strata (Stratum+) >
 
<!ELEMENT Stratum (Name, MorphologicalRuleDefinitions?, AffixTemplates?, LexicalEntries?) >
<!--
  characterDefinitionTable refers to a CharacterDefinitionTable ID
  -->
<!ATTLIST Stratum
  isActive (yes | no) "yes"
  characterDefinitionTable IDREF #REQUIRED
  cyclicity (cyclic | noncyclic) "noncyclic"
  phonologicalRuleOrder (linear | simultaneous) "linear"
  morphologicalRuleOrder (linear | unordered) "linear"
  phonologicalRules IDREFS #IMPLIED
  morphologicalRules IDREFS #IMPLIED
>

<!ELEMENT AffixTemplates (AffixTemplate+) >

<!ELEMENT AffixTemplate (Name, Slot+) >
<!--
  slots refers to one or more Slot IDs
  requiredPartsOfSpeech refers to one or more PartOfSpeech IDs
  requiredSubcategorizedRules refers to one or more SyntacticRule IDs
  -->
<!ATTLIST AffixTemplate 
  isActive (yes | no) "yes"
  final (true | false) "true"
  requiredPartsOfSpeech IDREFS #IMPLIED
  requiredSubcategorizedRules IDREFS #IMPLIED
>
<!ELEMENT Slot (Name) >
<!--
  morphologicalRules refers to one or more MorphologicalRule or RealizationalRule IDs; these are ordered
  -->
<!ATTLIST Slot
  isActive (yes | no) "yes"
  optional (true | false) "false"
  morphologicalRules IDREFS #REQUIRED
>

<!--
   =====================
   LexicalEntries
   =====================
-->
<!ELEMENT LexicalEntries (LexicalEntry+) >

<!ELEMENT LexicalEntry  (Allomorphs, AssignedHeadFeatures?, AssignedFootFeatures?, MorphemeId?, Gloss?, Properties?)>
<!--
    family refers to a family element ID
    partOfSpeech refers to a PartOfSpeech ID
    morphologicalRules refers to one or more MorphologicalRule, RealizationalRule and/or CompoundingRule IDs
    subcategorizations refers to one or more SyntacticRule IDs
    ruleFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs 
    obligatoryHeadFeatures refers to one or more (HeadFeature) FeatureDefinition IDs
    obligatoryFootFeatures refers to one or more (FootFeature) FeatureDefinition IDs
    -->
<!ATTLIST LexicalEntry
  id ID #REQUIRED
  isActive (yes | no) "yes"
  family IDREF #IMPLIED
  partOfSpeech IDREF #IMPLIED
  morphologicalRules IDREFS #IMPLIED
  subcategorizations IDREFS #IMPLIED
  ruleFeatures IDREFS #IMPLIED
  obligatoryHeadFeatures IDREFS #IMPLIED
  obligatoryFootFeatures IDREFS #IMPLIED
  partial (true | false) "false"
>

<!ELEMENT Allomorphs (Allomorph+) >

<!ELEMENT Allomorph (PhoneticShape, RequiredEnvironments?, ExcludedEnvironments?, Properties?) >
<!ATTLIST Allomorph
  id ID #REQUIRED
  isActive (yes | no) "yes"
  stemName IDREF #IMPLIED
  isBound (true | false) "false"
>

<!ELEMENT PhoneticShape (#PCDATA) >
<!ELEMENT Gloss (#PCDATA) >
<!ELEMENT MorphemeId (#PCDATA) >

<!ELEMENT AssignedHeadFeatures (FeatureValue+) >
<!ELEMENT AssignedFootFeatures (FeatureValue+) >

<!ELEMENT RequiredEnvironments (Environment+) >
<!ELEMENT ExcludedEnvironments (Environment+) >
<!ELEMENT Environment (LeftEnvironment?, RightEnvironment?) >

<!ELEMENT Properties (Property+) >
<!ELEMENT Property (#PCDATA) >
<!ATTLIST Property
  name CDATA #REQUIRED
 >

<!--
   =====================
   MorphologicalRuleDefinitions
   =====================
-->
<!ELEMENT MorphologicalRuleDefinitions (MorphologicalRule | RealizationalRule | CompoundingRule)* >

<!ELEMENT MorphologicalRule (Name, MorphologicalSubrules, OutputSubcategorizationOverrides?, OutputHeadFeatures?, OutputFootFeatures?, RequiredHeadFeatures?,
                             RequiredFootFeatures?, MorphemeId?, Gloss?, Properties?) >
<!--
  requiredPartsOfSpeech refers to one or more PartOfSpeech IDs
  requiredSubcategorizedRules refers to one or more SyntacticRule IDs
  outputPartOfSpeech refers to a PartOfSpeech ID
  outputSubcategorization refers to one or more SyntacticRule IDs
  outputObligatoryFeatures refers to one or more (HeadFeature) FeatureDefinition IDs
  (Note: what was Output Subcategorization (sub) in the text form of Hermit Crab has been split into
    the outputSubcategorization attribute plus the OutputSubcategorizationOverrides element (and its content).)
  -->
<!ATTLIST MorphologicalRule
  id ID #REQUIRED
  isActive (yes | no) "yes"
  blockable (true | false) "true"
  isCliticRule (true | false) #IMPLIED
  multipleApplication (0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9) "1"
  requiredPartsOfSpeech IDREFS #IMPLIED
  requiredSubcategorizedRules IDREFS #IMPLIED
  requiredStemName IDREF #IMPLIED
  outputPartOfSpeech IDREF #IMPLIED
  outputSubcategorization IDREFS #IMPLIED
  outputObligatoryFeatures IDREFS #IMPLIED
  partial (true | false) "false"
>

<!ELEMENT RealizationalRule (Name, MorphologicalSubrules, RealizationalFeatures?, RequiredHeadFeatures?, RequiredFootFeatures?, MorphemeId?, Gloss?, Properties?) >
<!ATTLIST RealizationalRule
  id ID #REQUIRED
  isActive (yes | no) "yes"
  blockable (true | false) "true"
  isCliticRule (true | false) #IMPLIED
>

<!--
  headPartsOfSpeech refers to one or more PartOfSpeech IDs
  nonheadPartsOfSpeech refers to one or more PartOfSpeech IDs
  headSubcategorizedRules refers to one or more SyntacticRule IDs
  nonheadSubcategorizedRules refers to one or more SyntacticRule IDs
  headProdRestrictionsMprFeatures refers to zero or more exception "features" IDs
  nonHeadProdRestrictionsMprFeatures refers to zero or more exception "features" IDs
  outputPartOfSpeech refers to a PartOfSpeech ID
  outputSubcategorization refers to one or more SyntacticRule IDs
  outputProdRestrictionsMprFeatures refers to zero or more exception "features" IDs
  outputObligatoryFeatures refers to one or more (HeadFeature) FeatureDefinition IDs
  (Note: what was Output Subcategorization (sub) in the text form of Hermit Crab has been split into
    the outputSubcategorization attribute plus the OutputSubcategorizationOverrides element (and its content).)
  -->
<!ELEMENT CompoundingRule (Name, CompoundingSubrules, OutputSubcategorizationOverrides?, OutputHeadFeatures?, OutputFootFeatures?,
                           HeadRequiredHeadFeatures?, NonHeadRequiredHeadFeatures?, HeadRequiredFootFeatures?, NonHeadRequiredFootFeatures?) >
<!ATTLIST CompoundingRule
  id ID #REQUIRED
  isActive (yes | no) "yes"
  blockable (true | false) "true"
  multipleApplication (0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9) "1"
  headPartsOfSpeech IDREFS #IMPLIED
  nonHeadPartsOfSpeech IDREFS #IMPLIED
  headSubcategorizedRules IDREFS #IMPLIED
  nonHeadSubcategorizedRules IDREFS #IMPLIED
  headProdRestrictionsMprFeatures IDREFS #IMPLIED
  nonHeadProdRestrictionsMprFeatures IDREFS #IMPLIED
  outputPartOfSpeech IDREF #IMPLIED
  outputSubcategorization IDREFS #IMPLIED
  outputProdRestrictionsMprFeatures IDREFS #IMPLIED
  outputObligatoryFeatures IDREFS #IMPLIED
>

<!ELEMENT MorphologicalSubrules (MorphologicalSubrule+) >
<!ELEMENT MorphologicalSubrule (VariableFeatures?, MorphologicalInput, MorphologicalOutput, RequiredHeadFeatures?, RequiredFootFeatures?,
                                RequiredEnvironments?, ExcludedEnvironments?, Properties?) >
<!ATTLIST MorphologicalSubrule
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!ELEMENT MorphologicalInput (PhoneticSequence+) >
<!--
    requiredMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
    excludedMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
-->
<!ATTLIST MorphologicalInput
  requiredMPRFeatures IDREFS #IMPLIED
  excludedMPRFeatures IDREFS #IMPLIED
>

<!ELEMENT MorphologicalOutput (CopyFromInput | InsertSimpleContext | ModifyFromInput | InsertSegments)* >
<!--
    MPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
-->
<!ATTLIST MorphologicalOutput
  MPRFeatures IDREFS #IMPLIED
  redupMorphType (prefix | suffix | implicit) "implicit"
>

<!ELEMENT CopyFromInput EMPTY>
<!--
  index refers to a RequiredPhoneticInput ID
  -->
<!ATTLIST CopyFromInput
  index IDREF #REQUIRED
>

<!ELEMENT InsertSimpleContext (SimpleContext) >

<!ELEMENT ModifyFromInput (SimpleContext)>
<!--
  index refers to a RequiredPhoneticInput ID
  -->
<!ATTLIST ModifyFromInput
  index IDREF #REQUIRED
>

<!ELEMENT InsertSegments (PhoneticShape) >
<!--
  characterDefinitionTable refers to a CharacterDefinitionTable ID
  -->
<!ATTLIST InsertSegments
  characterDefinitionTable IDREF #IMPLIED
>

<!ELEMENT VariableFeatures (VariableFeature+) >

<!ELEMENT VariableFeature EMPTY >
<!--
  phonologicalFeature refers to a (PhonologicalFeatureSystem) Feature ID
  -->
<!ATTLIST VariableFeature
  id ID #REQUIRED
  name (α | β | γ | δ | ε | ζ | η | θ | ι | κ | λ | μ | ν | ξ | ο | π | ρ | σ | τ | υ | φ | χ | ψ | ω) #REQUIRED
  phonologicalFeature IDREF #REQUIRED
>

<!--
 For OutputHeadFeatures and RequiredHeadFeatures, the Features need to be HeadFeatures. 
For OutputFootFeatures and RequiredFootFeatures, the Features need to be FootFeatures. 
-->
<!ELEMENT OutputHeadFeatures (FeatureValue+) >
<!ELEMENT OutputFootFeatures (FeatureValue+) >
<!ELEMENT RequiredHeadFeatures (FeatureValue+) >
<!ELEMENT RequiredFootFeatures (FeatureValue+) >
<!ELEMENT RealizationalFeatures (FeatureValue+) >
<!ELEMENT HeadRequiredHeadFeatures (FeatureValue+) >
<!ELEMENT HeadRequiredFootFeatures (FeatureValue+) >
<!ELEMENT NonHeadRequiredHeadFeatures (FeatureValue+) >
<!ELEMENT NonHeadRequiredFootFeatures (FeatureValue+) >
<!ELEMENT OutputSubcategorizationOverrides (OutputSubcategorizationOverride+) >
<!ELEMENT OutputSubcategorizationOverride EMPTY >
<!--
  inputSubcategorization refers to a SyntacticRule ID 
  outputSubcategorization refers to a SyntacticRule ID
  -->
<!ATTLIST OutputSubcategorizationOverride
  isActive (yes | no) "yes"
  inputSubcategorization IDREF #REQUIRED
  outputSubcategorization IDREF #IMPLIED
>

<!ELEMENT CompoundingSubrules (CompoundingSubrule+) >
<!ELEMENT CompoundingSubrule (VariableFeatures?, HeadMorphologicalInput, NonHeadMorphologicalInput, MorphologicalOutput) >
<!ATTLIST CompoundingSubrule
  isActive (yes | no) "yes"
>

<!ELEMENT HeadMorphologicalInput (PhoneticSequence+) >
<!--
    requiredMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
    excludedMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
-->
<!ATTLIST HeadMorphologicalInput
  requiredMPRFeatures IDREFS #IMPLIED
  excludedMPRFeatures IDREFS #IMPLIED
>

<!ELEMENT NonHeadMorphologicalInput (PhoneticSequence+) >

<!--
   =====================
   PhoneticSequence
   =====================
-->
<!ELEMENT PhoneticSequence (Segment | Segments | SimpleContext | OptionalSegmentSequence | BoundaryMarker)* >
<!ATTLIST PhoneticSequence
  id ID #IMPLIED
>
<!ELEMENT Segment EMPTY>
<!--
  The id is only needed for a metathesis rule
  segment refers to a SegmentDefinition ID
  -->
<!ATTLIST Segment
  id ID #IMPLIED
  segment IDREF #REQUIRED
>
<!ELEMENT Segments (PhoneticShape) >
<!ATTLIST Segments
  id ID #IMPLIED
  characterDefinitionTable IDREF #IMPLIED
>
<!ELEMENT BoundaryMarker EMPTY>
<!--
  The id is only needed for a metathesis rule
  boundary refers to a BoundaryDefinition ID
  -->
<!ATTLIST BoundaryMarker
  id ID #IMPLIED
  boundary IDREF #REQUIRED
>
<!ELEMENT SimpleContext (AlphaVariables?) >
<!--
  The id is only needed for a metathesis rule
  naturalClass refers to a NaturalClass ID
  -->
<!ATTLIST SimpleContext
  id ID #IMPLIED
  naturalClass IDREF #REQUIRED
>
<!ELEMENT AlphaVariables (AlphaVariable+)>
<!ELEMENT AlphaVariable EMPTY >
<!--
  variableFeature refers to a VariableFeature ID
  -->
<!ATTLIST AlphaVariable
  variableFeature IDREF #REQUIRED
  polarity (plus | minus) "plus"
>
<!ELEMENT OptionalSegmentSequence (Segment | Segments | SimpleContext | BoundaryMarker)+ >
<!--
  The id is only needed for a metathesis rule
  min is an integer, zero or higher 
  max is an integer, -1 or higher
  -->
<!ATTLIST OptionalSegmentSequence
  id ID #IMPLIED
  min CDATA #IMPLIED
  max CDATA #IMPLIED
>
<!ELEMENT PhoneticTemplate (PhoneticSequence) >
<!ATTLIST PhoneticTemplate
  initialBoundaryCondition (true | false) "false"
  finalBoundaryCondition (true | false) "false"
>

<!--
   =====================
   MorphemeCoOccurrenceRules
   =====================
-->
<!ELEMENT MorphemeCoOccurrenceRules (MorphemeCoOccurrenceRule+) >

<!ELEMENT MorphemeCoOccurrenceRule EMPTY >
<!ATTLIST MorphemeCoOccurrenceRule
  isActive (yes | no) "yes"
  type (exclude | require) "exclude"
  primaryMorpheme IDREF #REQUIRED
  otherMorphemes IDREFS #REQUIRED
  adjacency (anywhere | somewhereToLeft | somewhereToRight | adjacentToLeft | adjacentToRight) "anywhere"
>

<!--
   =====================
   AllomorphCoOccurrenceRules
   =====================
-->
<!ELEMENT AllomorphCoOccurrenceRules (AllomorphCoOccurrenceRule+) >

<!ELEMENT AllomorphCoOccurrenceRule EMPTY >
<!ATTLIST AllomorphCoOccurrenceRule
  isActive (yes | no) "yes"
  type (exclude | require) "exclude"
  primaryAllomorph IDREF #REQUIRED
  otherAllomorphs IDREFS #REQUIRED
  adjacency (anywhere | somewhereToLeft | somewhereToRight | adjacentToLeft | adjacentToRight) "anywhere"
>

<!--
   =====================
   SyntacticRules
   =====================
-->
<!ELEMENT SyntacticRules (SyntacticRule*) >
<!ELEMENT SyntacticRule (#PCDATA) >
<!ATTLIST SyntacticRule 
  id ID #REQUIRED
>

=== sillsdev/machine/conformance/edge-cases/right-to-left-metathesis-reversal/grammar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE HermitCrabInput SYSTEM "HermitCrabInput.dtd">
<HermitCrabInput>
  <Language>
    <Name>RightToLeftMetathesisReversal</Name>
    <!-- Synthetic construct-shaped mimic (docs/conformance/representative-typology-basis.md
         S1.2.4 - "Metathesis - right-to-left direction"; openspec/changes/
         plan-construct-coverage-completion task 4.6; docs/conformance/needs-decision-resolutions.md
         row 8). Invented CV roots only, no natural-language lexemes.

         Structural shape: one MetathesisRuleDef, multipleApplicationOrder="rightToLeftIterative",
         whose StructuralDescription is TWO adjacent SimpleContext switch positions, each a
         TWO-member natural class ({q,r} / {s,t}) - mirrors
         rust/crates/pg-foma/tests/phase_c_metathesis.rs's own MULTI_MEMBER_XML fixture (the
         per-branch literal cross-product precision witness), declared Dir::RightToLeft instead of
         the default Dir::LeftToRight that file already covers.

         Before openspec/changes/plan-construct-coverage-completion task 4.6,
         `crate::replace::compile_metathesis_rule` returned `Ok(None)` unconditionally for
         `Dir::RightToLeft` (an honest-unsupported scope boundary, not a wrong compile). Task 4.6
         built the SAME mirror-and-reverse construction `compile_rtl_branch_net` already uses for
         RTL *rewrite* rules (reverse the pattern's own slot order, remap the two switch indices to
         their mirrored positions, run the existing swap construction on the mirror, `fsm_reverse`
         the result, and `fsm_union` with the plain/LeftToRight-style net) - see
         `rust/crates/pg-foma/src/replace.rs`'s module doc, "Metathesis" section, and
         `crate::capability::MetathesisFaithfulSwapPredicate`'s own doc for the disposition
         (`ConfirmOnly`, never `Admit` - the union is a proven SUPERSET of the true RTL relation,
         not proven exact).

         Empirical finding while authoring this fixture (rust/crates/pg-foma tests, deleted
         throwaway probe): `pg_rules::metathesis::synthesize`'s own match-candidate selection
         (`match_candidates`'s ascending, direction-independent sort, in
         `rust/crates/pg-rules/src/metathesis.rs`) picks the LEFTMOST non-overlapping switch window
         regardless of `rule.dir`, for an overlapping-window probe - i.e. the real oracle is,
         empirically, direction-BLIND for metathesis today, the SAME shape
         `compile_rtl_branch_net`'s own doc found (before ITS OWN oracle fix) for ordinary
         `Iterative` rewrite rules. This grammar's own two lexical entries each have exactly ONE
         valid switch window (no overlap), so this empirical direction-blindness does not affect
         which surface each root resynthesizes to - oracle recall for BOTH roots here is identical
         to what the corresponding Dir::LeftToRight declaration would give. That is exactly why the
         FST-level "the construction genuinely differs from compiling as if LeftToRight" witness
         lives in `rust/crates/pg-foma/tests/phase_c_metathesis.rs` as a bare-automaton, oracle-free
         proof (mirroring `tests/phase_c_right_to_left.rs`'s own "aa -> b" worked example) rather
         than in this conformance fixture: this fixture's own job is the Stage-2 containment
         obligation (oracle recall subset-of FST propose), which holds regardless of whether the
         oracle happens to be direction-aware or -blind for the words it is asked about. -->
    <!-- G2a discipline (`conformance-staging/edge-cases/mpr-gated-exception`'s own authoring note):
         every segment needs a feature bundle that FULLY and UNIQUELY distinguishes it from every
         other segment, or a phonological-subrule reversal collapses feature-identical segments into
         a bracketed alternates class instead of the literal input string - the identical discipline
         `rust/crates/pg-foma/tests/phase_c_metathesis.rs`'s own fixtures already follow ("one
         distinct symbol value per segment"). -->
    <PartsOfSpeech>
      <PartOfSpeech id="posN"><Name>N</Name></PartOfSpeech>
    </PartsOfSpeech>
    <PhonologicalFeatureSystem>
      <SymbolicFeature id="featId">
        <Name>id</Name>
        <Symbols>
          <Symbol id="symQ">q</Symbol><Symbol id="symR">r</Symbol>
          <Symbol id="symS">s</Symbol><Symbol id="symT">t</Symbol>
        </Symbols>
      </SymbolicFeature>
    </PhonologicalFeatureSystem>
    <CharacterDefinitionTable id="t1">
      <Name>Main</Name>
      <SegmentDefinitions>
        <SegmentDefinition id="cQ"><Representations><Representation>q</Representation></Representations><FeatureValue feature="featId" symbolValues="symQ" /></SegmentDefinition>
        <SegmentDefinition id="cR"><Representations><Representation>r</Representation></Representations><FeatureValue feature="featId" symbolValues="symR" /></SegmentDefinition>
        <SegmentDefinition id="cS"><Representations><Representation>s</Representation></Representations><FeatureValue feature="featId" symbolValues="symS" /></SegmentDefinition>
        <SegmentDefinition id="cT"><Representations><Representation>t</Representation></Representations><FeatureValue feature="featId" symbolValues="symT" /></SegmentDefinition>
      </SegmentDefinitions>
    </CharacterDefinitionTable>
    <NaturalClasses>
      <SegmentNaturalClass id="ncSwitchA"><Name>SwitchA</Name><Segment segment="cQ" /><Segment segment="cR" /></SegmentNaturalClass>
      <SegmentNaturalClass id="ncSwitchB"><Name>SwitchB</Name><Segment segment="cS" /><Segment segment="cT" /></SegmentNaturalClass>
    </NaturalClasses>
    <PhonologicalRuleDefinitions>
      <MetathesisRule id="mrRtlReversal" leftSwitch="swB" rightSwitch="swA" multipleApplicationOrder="rightToLeftIterative">
        <Name>metathesisRtlReversal</Name>
        <StructuralDescription>
          <PhoneticTemplate>
            <PhoneticSequence>
              <SimpleContext id="swA" naturalClass="ncSwitchA" />
              <SimpleContext id="swB" naturalClass="ncSwitchB" />
            </PhoneticSequence>
          </PhoneticTemplate>
        </StructuralDescription>
      </MetathesisRule>
    </PhonologicalRuleDefinitions>
    <Strata>
      <Stratum characterDefinitionTable="t1" morphologicalRuleOrder="unordered" phonologicalRules="mrRtlReversal">
        <Name>Main</Name>
        <LexicalEntries>
          <LexicalEntry id="eRoot1">
            <Allomorphs><Allomorph id="aRoot1"><PhoneticShape>qs</PhoneticShape></Allomorph></Allomorphs>
            <MorphemeId>ROOT1</MorphemeId>
            <Gloss>root1</Gloss>
          </LexicalEntry>
          <LexicalEntry id="eRoot2">
            <Allomorphs><Allomorph id="aRoot2"><PhoneticShape>rt</PhoneticShape></Allomorph></Allomorphs>
            <MorphemeId>ROOT2</MorphemeId>
            <Gloss>root2</Gloss>
          </LexicalEntry>
        </LexicalEntries>
      </Stratum>
    </Strata>
  </Language>
</HermitCrabInput>
