=== sillsdev/machine/src/SIL.Machine.Morphology.HermitCrab/HermitCrabInput.dtd
<!-- Hermit Crab input file DTD
       Based on Maxwell, Mike.  1999.  "Hermit Crab Parsing Engine Specification."  SIL ms. 
-->
<!ELEMENT HermitCrabInput (Language+) >
<!ELEMENT Language (Name, PartsOfSpeech, PhonologicalFeatureSystem*, HeadFeatures?, FootFeatures?, MorphologicalPhonologicalRuleFeatures?, StemNames?, 
                    CharacterDefinitionTable+, NaturalClasses?, Families?, PhonologicalRuleDefinitions?, Strata, MorphemeCoOccurrenceRules?, AllomorphCoOccurrenceRules?, SyntacticRules?) >
<!--
  Note: at most one should be active at a time
  -->
<!ATTLIST Language
  isActive (yes | no) "yes"
>

<!--
   =====================
   PartsOfSpeech
   =====================
-->
<!ELEMENT PartsOfSpeech (PartOfSpeech+) >
<!ELEMENT PartOfSpeech (Name) >
<!ATTLIST PartOfSpeech
  id ID #REQUIRED
>

<!--
   =====================
   FeatureSystems
   =====================
-->
<!ELEMENT PhonologicalFeatureSystem (SymbolicFeature*) >
<!--
  Note: at most one should be active at a time
  -->
<!ATTLIST PhonologicalFeatureSystem
  isActive (yes | no) "yes"
>
<!ELEMENT HeadFeatures ((SymbolicFeature | ComplexFeature)*) >
<!ELEMENT FootFeatures ((SymbolicFeature | ComplexFeature)*) >

<!ELEMENT SymbolicFeature (Name, Symbols) >
<!ATTLIST SymbolicFeature
  id ID #REQUIRED
  isActive (yes | no) "yes"
  defaultSymbol IDREF #IMPLIED
>
<!-- Note: for phonlogical features like [son:+] and [nas:+], we create separate values for "+"; potentially we could reuse them -->
<!ELEMENT Symbols (Symbol+) >
<!ELEMENT Symbol (#PCDATA) >
<!ATTLIST Symbol
  id ID #REQUIRED
>

<!ELEMENT ComplexFeature (Name) >
<!ATTLIST ComplexFeature
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!ELEMENT FeatureValue (FeatureValue*)>
<!--
  feature refers to a SymbolicFeature or ComplexFeature ID
  symbolValues refers to one or more Symbol IDs
  -->
<!ATTLIST FeatureValue
  isActive (yes | no) "yes"
  feature IDREF #REQUIRED
  symbolValues IDREFS #IMPLIED
>

<!--
   =====================
   MorphologicalPhonologicalRuleFeatures
   =====================
-->
<!ELEMENT MorphologicalPhonologicalRuleFeatures (MorphologicalPhonologicalRuleFeature+, MorphologicalPhonologicalRuleFeatureGroup*) >
<!ELEMENT MorphologicalPhonologicalRuleFeature (#PCDATA) >
<!ATTLIST MorphologicalPhonologicalRuleFeature
  id ID #REQUIRED
  isActive (yes | no) "yes"
>
<!ELEMENT MorphologicalPhonologicalRuleFeatureGroup (Name)>
<!ATTLIST MorphologicalPhonologicalRuleFeatureGroup
  isActive (yes | no) "yes"
  matchType (any | all) "any"
  outputType (overwrite | append) "overwrite"
  features IDREFS #REQUIRED
>

<!--
   =====================
   StemNames
   =====================
-->
<!ELEMENT StemNames (StemName+) >
<!ELEMENT StemName (Name, Regions) >
<!ATTLIST StemName
  id ID #REQUIRED
  partsOfSpeech IDREFS #REQUIRED
>
<!ELEMENT Regions (Region+) >
<!ELEMENT Region (AssignedHeadFeatures?, AssignedFootFeatures?) >

<!--
   =====================
   CharacterDefinitionTable
   =====================
-->
<!ELEMENT CharacterDefinitionTable (Name, SegmentDefinitions, BoundaryDefinitions? ) >
<!ATTLIST CharacterDefinitionTable
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!ELEMENT Name (#PCDATA) >

<!ELEMENT SegmentDefinitions (SegmentDefinition+) >

<!ELEMENT SegmentDefinition (Representations, FeatureValue*) >
<!ATTLIST SegmentDefinition
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!ELEMENT Representations (Representation+) >

<!ELEMENT Representation (#PCDATA) >

<!ELEMENT BoundaryDefinitions (BoundaryDefinition+) >

<!ELEMENT BoundaryDefinition (Representations) >
<!ATTLIST BoundaryDefinition
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!--
   =====================
   NaturalClasses
   =====================
-->
<!ELEMENT NaturalClasses (FeatureNaturalClass | SegmentNaturalClass)+ >

<!ELEMENT FeatureNaturalClass (Name, FeatureValue*) >
<!ATTLIST FeatureNaturalClass 
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!ELEMENT SegmentNaturalClass (Name, Segment*) >
<!ATTLIST SegmentNaturalClass 
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!--
   =====================
   Families
   =====================
-->
<!-- Families are used to block analyses for irregular forms (e.g. preventing the regular form from also analyzing) -->
<!ELEMENT Families (Family*) >
<!ELEMENT Family (#PCDATA) >
<!ATTLIST Family
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!--
   =====================
   PhonologicalRuleDefinitions
   =====================
-->
<!ELEMENT PhonologicalRuleDefinitions (PhonologicalRule | MetathesisRule)*>

<!ELEMENT PhonologicalRule (Name, VariableFeatures?, PhoneticInput, PhonologicalSubrules)>
<!ATTLIST PhonologicalRule
  id ID #REQUIRED
  isActive (yes | no) "yes"
  multipleApplicationOrder (leftToRightIterative | rightToLeftIterative | simultaneous) "leftToRightIterative"
>

<!ELEMENT PhoneticInput (PhoneticSequence?) >

<!ELEMENT PhonologicalSubrules (PhonologicalSubrule+) >
<!ELEMENT PhonologicalSubrule (PhoneticOutput, Environment?, PreviousWord?, NextWord?) >
<!--
  requiredPartsOfSpeech refers to one or more PartOfSpeech IDs
  requiredMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
  excludedMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
-->  
<!ATTLIST PhonologicalSubrule
  isActive (yes | no) "yes"
  requiredPartsOfSpeech IDREFS #IMPLIED
  requiredMPRFeatures IDREFS #IMPLIED
  excludedMPRFeatures IDREFS #IMPLIED
>

<!ELEMENT PhoneticOutput (PhoneticSequence?) >
  
<!ELEMENT LeftEnvironment (PhoneticTemplate) >
<!ELEMENT RightEnvironment (PhoneticTemplate) >

<!ELEMENT PreviousWord (PhoneticTemplate | Null) >
<!ATTLIST PreviousWord
  id ID #REQUIRED
  >
<!ELEMENT NextWord (PhoneticTemplate | Null) >
<!ATTLIST NextWord
  id ID #REQUIRED
  >

<!ELEMENT Null EMPTY >
<!ATTLIST Null
  id ID #REQUIRED
>

<!ELEMENT MetathesisRule (Name, StructuralDescription) >
<!ATTLIST MetathesisRule
  isActive (yes | no) "yes"
  id ID #REQUIRED
  leftSwitch IDREF #REQUIRED
  rightSwitch IDREF #REQUIRED
  multipleApplicationOrder (leftToRightIterative | rightToLeftIterative) "leftToRightIterative"
>

<!ELEMENT StructuralDescription (PhoneticTemplate) >

<!--
   =====================
   Strata
   =====================
-->
<!ELEMENT Strata (Stratum+) >
 
<!ELEMENT Stratum (Name, MorphologicalRuleDefinitions?, AffixTemplates?, LexicalEntries?) >
<!--
  characterDefinitionTable refers to a CharacterDefinitionTable ID
  -->
<!ATTLIST Stratum
  isActive (yes | no) "yes"
  characterDefinitionTable IDREF #REQUIRED
  cyclicity (cyclic | noncyclic) "noncyclic"
  phonologicalRuleOrder (linear | simultaneous) "linear"
  morphologicalRuleOrder (linear | unordered) "linear"
  phonologicalRules IDREFS #IMPLIED
  morphologicalRules IDREFS #IMPLIED
>

<!ELEMENT AffixTemplates (AffixTemplate+) >

<!ELEMENT AffixTemplate (Name, Slot+) >
<!--
  slots refers to one or more Slot IDs
  requiredPartsOfSpeech refers to one or more PartOfSpeech IDs
  requiredSubcategorizedRules refers to one or more SyntacticRule IDs
  -->
<!ATTLIST AffixTemplate 
  isActive (yes | no) "yes"
  final (true | false) "true"
  requiredPartsOfSpeech IDREFS #IMPLIED
  requiredSubcategorizedRules IDREFS #IMPLIED
>
<!ELEMENT Slot (Name) >
<!--
  morphologicalRules refers to one or more MorphologicalRule or RealizationalRule IDs; these are ordered
  -->
<!ATTLIST Slot
  isActive (yes | no) "yes"
  optional (true | false) "false"
  morphologicalRules IDREFS #REQUIRED
>

<!--
   =====================
   LexicalEntries
   =====================
-->
<!ELEMENT LexicalEntries (LexicalEntry+) >

<!ELEMENT LexicalEntry  (Allomorphs, AssignedHeadFeatures?, AssignedFootFeatures?, MorphemeId?, Gloss?, Properties?)>
<!--
    family refers to a family element ID
    partOfSpeech refers to a PartOfSpeech ID
    morphologicalRules refers to one or more MorphologicalRule, RealizationalRule and/or CompoundingRule IDs
    subcategorizations refers to one or more SyntacticRule IDs
    ruleFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs 
    obligatoryHeadFeatures refers to one or more (HeadFeature) FeatureDefinition IDs
    obligatoryFootFeatures refers to one or more (FootFeature) FeatureDefinition IDs
    -->
<!ATTLIST LexicalEntry
  id ID #REQUIRED
  isActive (yes | no) "yes"
  family IDREF #IMPLIED
  partOfSpeech IDREF #IMPLIED
  morphologicalRules IDREFS #IMPLIED
  subcategorizations IDREFS #IMPLIED
  ruleFeatures IDREFS #IMPLIED
  obligatoryHeadFeatures IDREFS #IMPLIED
  obligatoryFootFeatures IDREFS #IMPLIED
  partial (true | false) "false"
>

<!ELEMENT Allomorphs (Allomorph+) >

<!ELEMENT Allomorph (PhoneticShape, RequiredEnvironments?, ExcludedEnvironments?, Properties?) >
<!ATTLIST Allomorph
  id ID #REQUIRED
  isActive (yes | no) "yes"
  stemName IDREF #IMPLIED
  isBound (true | false) "false"
>

<!ELEMENT PhoneticShape (#PCDATA) >
<!ELEMENT Gloss (#PCDATA) >
<!ELEMENT MorphemeId (#PCDATA) >

<!ELEMENT AssignedHeadFeatures (FeatureValue+) >
<!ELEMENT AssignedFootFeatures (FeatureValue+) >

<!ELEMENT RequiredEnvironments (Environment+) >
<!ELEMENT ExcludedEnvironments (Environment+) >
<!ELEMENT Environment (LeftEnvironment?, RightEnvironment?) >

<!ELEMENT Properties (Property+) >
<!ELEMENT Property (#PCDATA) >
<!ATTLIST Property
  name CDATA #REQUIRED
 >

<!--
   =====================
   MorphologicalRuleDefinitions
   =====================
-->
<!ELEMENT MorphologicalRuleDefinitions (MorphologicalRule | RealizationalRule | CompoundingRule)* >

<!ELEMENT MorphologicalRule (Name, MorphologicalSubrules, OutputSubcategorizationOverrides?, OutputHeadFeatures?, OutputFootFeatures?, RequiredHeadFeatures?,
                             RequiredFootFeatures?, MorphemeId?, Gloss?, Properties?) >
<!--
  requiredPartsOfSpeech refers to one or more PartOfSpeech IDs
  requiredSubcategorizedRules refers to one or more SyntacticRule IDs
  outputPartOfSpeech refers to a PartOfSpeech ID
  outputSubcategorization refers to one or more SyntacticRule IDs
  outputObligatoryFeatures refers to one or more (HeadFeature) FeatureDefinition IDs
  (Note: what was Output Subcategorization (sub) in the text form of Hermit Crab has been split into
    the outputSubcategorization attribute plus the OutputSubcategorizationOverrides element (and its content).)
  -->
<!ATTLIST MorphologicalRule
  id ID #REQUIRED
  isActive (yes | no) "yes"
  blockable (true | false) "true"
  isCliticRule (true | false) #IMPLIED
  multipleApplication (0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9) "1"
  requiredPartsOfSpeech IDREFS #IMPLIED
  requiredSubcategorizedRules IDREFS #IMPLIED
  requiredStemName IDREF #IMPLIED
  outputPartOfSpeech IDREF #IMPLIED
  outputSubcategorization IDREFS #IMPLIED
  outputObligatoryFeatures IDREFS #IMPLIED
  partial (true | false) "false"
>

<!ELEMENT RealizationalRule (Name, MorphologicalSubrules, RealizationalFeatures?, RequiredHeadFeatures?, RequiredFootFeatures?, MorphemeId?, Gloss?, Properties?) >
<!ATTLIST RealizationalRule
  id ID #REQUIRED
  isActive (yes | no) "yes"
  blockable (true | false) "true"
  isCliticRule (true | false) #IMPLIED
>

<!--
  headPartsOfSpeech refers to one or more PartOfSpeech IDs
  nonheadPartsOfSpeech refers to one or more PartOfSpeech IDs
  headSubcategorizedRules refers to one or more SyntacticRule IDs
  nonheadSubcategorizedRules refers to one or more SyntacticRule IDs
  headProdRestrictionsMprFeatures refers to zero or more exception "features" IDs
  nonHeadProdRestrictionsMprFeatures refers to zero or more exception "features" IDs
  outputPartOfSpeech refers to a PartOfSpeech ID
  outputSubcategorization refers to one or more SyntacticRule IDs
  outputProdRestrictionsMprFeatures refers to zero or more exception "features" IDs
  outputObligatoryFeatures refers to one or more (HeadFeature) FeatureDefinition IDs
  (Note: what was Output Subcategorization (sub) in the text form of Hermit Crab has been split into
    the outputSubcategorization attribute plus the OutputSubcategorizationOverrides element (and its content).)
  -->
<!ELEMENT CompoundingRule (Name, CompoundingSubrules, OutputSubcategorizationOverrides?, OutputHeadFeatures?, OutputFootFeatures?,
                           HeadRequiredHeadFeatures?, NonHeadRequiredHeadFeatures?, HeadRequiredFootFeatures?, NonHeadRequiredFootFeatures?) >
<!ATTLIST CompoundingRule
  id ID #REQUIRED
  isActive (yes | no) "yes"
  blockable (true | false) "true"
  multipleApplication (0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9) "1"
  headPartsOfSpeech IDREFS #IMPLIED
  nonHeadPartsOfSpeech IDREFS #IMPLIED
  headSubcategorizedRules IDREFS #IMPLIED
  nonHeadSubcategorizedRules IDREFS #IMPLIED
  headProdRestrictionsMprFeatures IDREFS #IMPLIED
  nonHeadProdRestrictionsMprFeatures IDREFS #IMPLIED
  outputPartOfSpeech IDREF #IMPLIED
  outputSubcategorization IDREFS #IMPLIED
  outputProdRestrictionsMprFeatures IDREFS #IMPLIED
  outputObligatoryFeatures IDREFS #IMPLIED
>

<!ELEMENT MorphologicalSubrules (MorphologicalSubrule+) >
<!ELEMENT MorphologicalSubrule (VariableFeatures?, MorphologicalInput, MorphologicalOutput, RequiredHeadFeatures?, RequiredFootFeatures?,
                                RequiredEnvironments?, ExcludedEnvironments?, Properties?) >
<!ATTLIST MorphologicalSubrule
  id ID #REQUIRED
  isActive (yes | no) "yes"
>

<!ELEMENT MorphologicalInput (PhoneticSequence+) >
<!--
    requiredMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
    excludedMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
-->
<!ATTLIST MorphologicalInput
  requiredMPRFeatures IDREFS #IMPLIED
  excludedMPRFeatures IDREFS #IMPLIED
>

<!ELEMENT MorphologicalOutput (CopyFromInput | InsertSimpleContext | ModifyFromInput | InsertSegments)* >
<!--
    MPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
-->
<!ATTLIST MorphologicalOutput
  MPRFeatures IDREFS #IMPLIED
  redupMorphType (prefix | suffix | implicit) "implicit"
>

<!ELEMENT CopyFromInput EMPTY>
<!--
  index refers to a RequiredPhoneticInput ID
  -->
<!ATTLIST CopyFromInput
  index IDREF #REQUIRED
>

<!ELEMENT InsertSimpleContext (SimpleContext) >

<!ELEMENT ModifyFromInput (SimpleContext)>
<!--
  index refers to a RequiredPhoneticInput ID
  -->
<!ATTLIST ModifyFromInput
  index IDREF #REQUIRED
>

<!ELEMENT InsertSegments (PhoneticShape) >
<!--
  characterDefinitionTable refers to a CharacterDefinitionTable ID
  -->
<!ATTLIST InsertSegments
  characterDefinitionTable IDREF #IMPLIED
>

<!ELEMENT VariableFeatures (VariableFeature+) >

<!ELEMENT VariableFeature EMPTY >
<!--
  phonologicalFeature refers to a (PhonologicalFeatureSystem) Feature ID
  -->
<!ATTLIST VariableFeature
  id ID #REQUIRED
  name (α | β | γ | δ | ε | ζ | η | θ | ι | κ | λ | μ | ν | ξ | ο | π | ρ | σ | τ | υ | φ | χ | ψ | ω) #REQUIRED
  phonologicalFeature IDREF #REQUIRED
>

<!--
 For OutputHeadFeatures and RequiredHeadFeatures, the Features need to be HeadFeatures. 
For OutputFootFeatures and RequiredFootFeatures, the Features need to be FootFeatures. 
-->
<!ELEMENT OutputHeadFeatures (FeatureValue+) >
<!ELEMENT OutputFootFeatures (FeatureValue+) >
<!ELEMENT RequiredHeadFeatures (FeatureValue+) >
<!ELEMENT RequiredFootFeatures (FeatureValue+) >
<!ELEMENT RealizationalFeatures (FeatureValue+) >
<!ELEMENT HeadRequiredHeadFeatures (FeatureValue+) >
<!ELEMENT HeadRequiredFootFeatures (FeatureValue+) >
<!ELEMENT NonHeadRequiredHeadFeatures (FeatureValue+) >
<!ELEMENT NonHeadRequiredFootFeatures (FeatureValue+) >
<!ELEMENT OutputSubcategorizationOverrides (OutputSubcategorizationOverride+) >
<!ELEMENT OutputSubcategorizationOverride EMPTY >
<!--
  inputSubcategorization refers to a SyntacticRule ID 
  outputSubcategorization refers to a SyntacticRule ID
  -->
<!ATTLIST OutputSubcategorizationOverride
  isActive (yes | no) "yes"
  inputSubcategorization IDREF #REQUIRED
  outputSubcategorization IDREF #IMPLIED
>

<!ELEMENT CompoundingSubrules (CompoundingSubrule+) >
<!ELEMENT CompoundingSubrule (VariableFeatures?, HeadMorphologicalInput, NonHeadMorphologicalInput, MorphologicalOutput) >
<!ATTLIST CompoundingSubrule
  isActive (yes | no) "yes"
>

<!ELEMENT HeadMorphologicalInput (PhoneticSequence+) >
<!--
    requiredMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
    excludedMPRFeatures refers to one or more MorphologicalPhonologicalRuleFeature IDs
-->
<!ATTLIST HeadMorphologicalInput
  requiredMPRFeatures IDREFS #IMPLIED
  excludedMPRFeatures IDREFS #IMPLIED
>

<!ELEMENT NonHeadMorphologicalInput (PhoneticSequence+) >

<!--
   =====================
   PhoneticSequence
   =====================
-->
<!ELEMENT PhoneticSequence (Segment | Segments | SimpleContext | OptionalSegmentSequence | BoundaryMarker)* >
<!ATTLIST PhoneticSequence
  id ID #IMPLIED
>
<!ELEMENT Segment EMPTY>
<!--
  The id is only needed for a metathesis rule
  segment refers to a SegmentDefinition ID
  -->
<!ATTLIST Segment
  id ID #IMPLIED
  segment IDREF #REQUIRED
>
<!ELEMENT Segments (PhoneticShape) >
<!ATTLIST Segments
  id ID #IMPLIED
  characterDefinitionTable IDREF #IMPLIED
>
<!ELEMENT BoundaryMarker EMPTY>
<!--
  The id is only needed for a metathesis rule
  boundary refers to a BoundaryDefinition ID
  -->
<!ATTLIST BoundaryMarker
  id ID #IMPLIED
  boundary IDREF #REQUIRED
>
<!ELEMENT SimpleContext (AlphaVariables?) >
<!--
  The id is only needed for a metathesis rule
  naturalClass refers to a NaturalClass ID
  -->
<!ATTLIST SimpleContext
  id ID #IMPLIED
  naturalClass IDREF #REQUIRED
>
<!ELEMENT AlphaVariables (AlphaVariable+)>
<!ELEMENT AlphaVariable EMPTY >
<!--
  variableFeature refers to a VariableFeature ID
  -->
<!ATTLIST AlphaVariable
  variableFeature IDREF #REQUIRED
  polarity (plus | minus) "plus"
>
<!ELEMENT OptionalSegmentSequence (Segment | Segments | SimpleContext | BoundaryMarker)+ >
<!--
  The id is only needed for a metathesis rule
  min is an integer, zero or higher 
  max is an integer, -1 or higher
  -->
<!ATTLIST OptionalSegmentSequence
  id ID #IMPLIED
  min CDATA #IMPLIED
  max CDATA #IMPLIED
>
<!ELEMENT PhoneticTemplate (PhoneticSequence) >
<!ATTLIST PhoneticTemplate
  initialBoundaryCondition (true | false) "false"
  finalBoundaryCondition (true | false) "false"
>

<!--
   =====================
   MorphemeCoOccurrenceRules
   =====================
-->
<!ELEMENT MorphemeCoOccurrenceRules (MorphemeCoOccurrenceRule+) >

<!ELEMENT MorphemeCoOccurrenceRule EMPTY >
<!ATTLIST MorphemeCoOccurrenceRule
  isActive (yes | no) "yes"
  type (exclude | require) "exclude"
  primaryMorpheme IDREF #REQUIRED
  otherMorphemes IDREFS #REQUIRED
  adjacency (anywhere | somewhereToLeft | somewhereToRight | adjacentToLeft | adjacentToRight) "anywhere"
>

<!--
   =====================
   AllomorphCoOccurrenceRules
   =====================
-->
<!ELEMENT AllomorphCoOccurrenceRules (AllomorphCoOccurrenceRule+) >

<!ELEMENT AllomorphCoOccurrenceRule EMPTY >
<!ATTLIST AllomorphCoOccurrenceRule
  isActive (yes | no) "yes"
  type (exclude | require) "exclude"
  primaryAllomorph IDREF #REQUIRED
  otherAllomorphs IDREFS #REQUIRED
  adjacency (anywhere | somewhereToLeft | somewhereToRight | adjacentToLeft | adjacentToRight) "anywhere"
>

<!--
   =====================
   SyntacticRules
   =====================
-->
<!ELEMENT SyntacticRules (SyntacticRule*) >
<!ELEMENT SyntacticRule (#PCDATA) >
<!ATTLIST SyntacticRule 
  id ID #REQUIRED
>

=== sillsdev/machine/conformance/edge-cases/cross-table-root-respelling/grammar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE HermitCrabInput SYSTEM "HermitCrabInput.dtd">
<HermitCrabInput>
  <Language>
    <Name>CrossTableRootRespelling</Name>
    <!-- Isolates cross-table RESPELLING with NO phonological rule anywhere in the grammar: the
         mechanism is a loader/lookup fact, not a rewrite-rule side effect. In HermitCrab a segment
         IS its feature bundle; a CharacterDefinitionTable only spells that bundle for its own
         stratum (CharacterDefinitionTable.GetMatchingStrReps, matching by
         `FeatureStruct.IsUnifiable` alone). So a root entered on an inner stratum surfaces spelled
         by whichever FINAL-stratum segment carries the SAME bundle, even when the two tables never
         share a single character. This differs from edge-cases/bistratal-overlapping-segment-
         representation (that fixture's two tables OVERLAP in spelling, e.g. both declare "s", and
         pins that overlapping spelling does NOT imply overlapping identity); here the tables'
         alphabets are disjoint (Inner: m/q, Final: t/s/u) precisely so no spelling can be mistaken
         for the mechanism: only bundle equality reaches across.

         Two features (featA, featB), each binary, give four distinct bundles:
           X = (a1,b1), Y = (a2,b1), Z = (a1,b2), W = (a2,b2)
         Inner table (tIn):  cA1 "m" = X,  cA2 "q" = Y
         Final table (tFin): cB1 "t" = X,  cB2 "s" = Z,  cC1 "u" = W (suffix material only)
         tFin has NO segment carrying Y: the deliberate asymmetry the fixture is built to show.

         ROOT1 ("m", tIn, bundle X) has no representation in tFin's own alphabet, yet surfaces as
         "t" (cB1, same bundle X) with no rule involved: the positive witness. ROOT2 ("q", tIn,
         bundle Y) can NEVER surface: no tFin segment carries Y, so no string over tFin's alphabet
         can ever unify with it at lexical lookup, regardless of spelling; pinned by typing its
         own raw shape at the surface and transcribing whatever the oracle reports (tFin does not
         even declare "q" as a character, so tokenization itself fails). ROOT3 ("t", tFin, bundle X)
         is a NATIVE Final-stratum entry that happens to share ROOT1's respelled surface, so "t" is
         AMBIGUOUS: respelling coexists with, and is not shadowed by, a native root at the same
         surface spelling. mrSuffix (Final stratum only) appends "u" (cC1) to any posV stem, so "tu"
         exercises respelling surviving under affixation. -->
    <PartsOfSpeech>
      <PartOfSpeech id="posV"><Name>V</Name></PartOfSpeech>
    </PartsOfSpeech>
    <PhonologicalFeatureSystem>
      <SymbolicFeature id="featA">
        <Name>A</Name>
        <Symbols>
          <Symbol id="symA1">a1</Symbol>
          <Symbol id="symA2">a2</Symbol>
        </Symbols>
      </SymbolicFeature>
      <SymbolicFeature id="featB">
        <Name>B</Name>
        <Symbols>
          <Symbol id="symB1">b1</Symbol>
          <Symbol id="symB2">b2</Symbol>
        </Symbols>
      </SymbolicFeature>
    </PhonologicalFeatureSystem>
    <CharacterDefinitionTable id="tIn">
      <Name>Inner</Name>
      <SegmentDefinitions>
        <SegmentDefinition id="cA1">
          <Representations><Representation>m</Representation></Representations>
          <FeatureValue feature="featA" symbolValues="symA1" />
          <FeatureValue feature="featB" symbolValues="symB1" />
        </SegmentDefinition>
        <SegmentDefinition id="cA2">
          <Representations><Representation>q</Representation></Representations>
          <FeatureValue feature="featA" symbolValues="symA2" />
          <FeatureValue feature="featB" symbolValues="symB1" />
        </SegmentDefinition>
      </SegmentDefinitions>
    </CharacterDefinitionTable>
    <CharacterDefinitionTable id="tFin">
      <Name>Final</Name>
      <SegmentDefinitions>
        <SegmentDefinition id="cB1">
          <Representations><Representation>t</Representation></Representations>
          <FeatureValue feature="featA" symbolValues="symA1" />
          <FeatureValue feature="featB" symbolValues="symB1" />
        </SegmentDefinition>
        <SegmentDefinition id="cB2">
          <Representations><Representation>s</Representation></Representations>
          <FeatureValue feature="featA" symbolValues="symA1" />
          <FeatureValue feature="featB" symbolValues="symB2" />
        </SegmentDefinition>
        <SegmentDefinition id="cC1">
          <Representations><Representation>u</Representation></Representations>
          <FeatureValue feature="featA" symbolValues="symA2" />
          <FeatureValue feature="featB" symbolValues="symB2" />
        </SegmentDefinition>
      </SegmentDefinitions>
    </CharacterDefinitionTable>
    <NaturalClasses>
      <!-- Universal "matches any single segment" class, used only to write mrSuffix's stem pattern;
           carries no FeatureValue constraints, so it is not part of the respelling mechanism. -->
      <FeatureNaturalClass id="ncAny"><Name>Any</Name></FeatureNaturalClass>
    </NaturalClasses>
    <Strata>
      <Stratum characterDefinitionTable="tIn" morphologicalRuleOrder="unordered">
        <Name>Inner</Name>
        <LexicalEntries>
          <LexicalEntry id="eRoot1" partOfSpeech="posV">
            <Allomorphs><Allomorph id="aRoot1"><PhoneticShape>m</PhoneticShape></Allomorph></Allomorphs>
            <MorphemeId>ROOT1</MorphemeId>
            <Gloss>root1</Gloss>
          </LexicalEntry>
          <LexicalEntry id="eRoot2" partOfSpeech="posV">
            <Allomorphs><Allomorph id="aRoot2"><PhoneticShape>q</PhoneticShape></Allomorph></Allomorphs>
            <MorphemeId>ROOT2</MorphemeId>
            <Gloss>root2</Gloss>
          </LexicalEntry>
        </LexicalEntries>
      </Stratum>
      <Stratum characterDefinitionTable="tFin" morphologicalRuleOrder="unordered" morphologicalRules="mrSuffix">
        <Name>Final</Name>
        <MorphologicalRuleDefinitions>
          <MorphologicalRule id="mrSuffix" requiredPartsOfSpeech="posV" outputPartOfSpeech="posV">
            <Name>suffix</Name>
            <MorphologicalSubrules>
              <MorphologicalSubrule id="msSuffix">
                <MorphologicalInput>
                  <PhoneticSequence id="stem"><SimpleContext naturalClass="ncAny" /></PhoneticSequence>
                </MorphologicalInput>
                <MorphologicalOutput>
                  <CopyFromInput index="stem" /><InsertSegments><PhoneticShape>u</PhoneticShape></InsertSegments>
                </MorphologicalOutput>
              </MorphologicalSubrule>
            </MorphologicalSubrules>
            <MorphemeId>SUF</MorphemeId>
            <Gloss>suf</Gloss>
          </MorphologicalRule>
        </MorphologicalRuleDefinitions>
        <LexicalEntries>
          <LexicalEntry id="eRoot3" partOfSpeech="posV">
            <Allomorphs><Allomorph id="aRoot3"><PhoneticShape>t</PhoneticShape></Allomorph></Allomorphs>
            <MorphemeId>ROOT3</MorphemeId>
            <Gloss>root3</Gloss>
          </LexicalEntry>
        </LexicalEntries>
      </Stratum>
    </Strata>
  </Language>
</HermitCrabInput>
